if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER12_SVD17'
'TEXTCLUSTER12_SVD2'
'TEXTCLUSTER12_SVD22'
'TEXTCLUSTER12_SVD3'
'TEXTCLUSTER12_SVD4'
'TEXTCLUSTER12_SVD5'
'TEXTCLUSTER12_SVD7'
'TEXTCLUSTER12_SVD8'
'TEXTCLUSTER12_SVD9'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg8: Rejected using stepwise selection";
end;
end;
