if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER6_SVD10'
'TEXTCLUSTER6_SVD11'
'TEXTCLUSTER6_SVD14'
'TEXTCLUSTER6_SVD2'
'TEXTCLUSTER6_SVD24'
'TEXTCLUSTER6_SVD3'
'TEXTCLUSTER6_SVD4'
'TEXTCLUSTER6_SVD5'
'TEXTCLUSTER6_SVD7'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg6: Rejected using stepwise selection";
end;
end;
