if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER4_SVD10'
'TEXTCLUSTER4_SVD12'
'TEXTCLUSTER4_SVD15'
'TEXTCLUSTER4_SVD2'
'TEXTCLUSTER4_SVD25'
'TEXTCLUSTER4_SVD3'
'TEXTCLUSTER4_SVD4'
'TEXTCLUSTER4_SVD5'
'TEXTCLUSTER4_SVD6'
'TEXTCLUSTER4_SVD7'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg: Rejected using stepwise selection";
end;
end;
