if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER9_SVD2'
'TEXTCLUSTER9_SVD22'
'TEXTCLUSTER9_SVD3'
'TEXTCLUSTER9_SVD4'
'TEXTCLUSTER9_SVD5'
'TEXTCLUSTER9_SVD7'
'TEXTCLUSTER9_SVD8'
'TEXTCLUSTER9_SVD9'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg9: Rejected using stepwise selection";
end;
end;
