if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER8_SVD10'
'TEXTCLUSTER8_SVD11'
'TEXTCLUSTER8_SVD14'
'TEXTCLUSTER8_SVD2'
'TEXTCLUSTER8_SVD24'
'TEXTCLUSTER8_SVD3'
'TEXTCLUSTER8_SVD4'
'TEXTCLUSTER8_SVD5'
'TEXTCLUSTER8_SVD7'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg5: Rejected using stepwise selection";
end;
end;
