****************************************************************;
******             DECISION TREE SCORING CODE             ******;
****************************************************************;

******         LENGTHS OF NEW CHARACTER VARIABLES         ******;
LENGTH I_Category  $   22; 
LENGTH U_Category  $   22; 
LENGTH _WARN_  $    4; 

******              LABELS FOR NEW VARIABLES              ******;
label _NODE_ = 'Node' ;
label _LEAF_ = 'Leaf' ;
label P_CategoryHR = 'Predicted: Category=HR' ;
label P_CategoryDESIGNER = 'Predicted: Category=DESIGNER' ;
label P_CategoryINFORMATION_TECHNOLOGY = 
'Predicted: Category=INFORMATION-TECHNOLOGY' ;
label P_CategoryTEACHER = 'Predicted: Category=TEACHER' ;
label P_CategoryADVOCATE = 'Predicted: Category=ADVOCATE' ;
label P_CategoryBUSINESS_DEVELOPMENT = 
'Predicted: Category=BUSINESS-DEVELOPMENT' ;
label P_CategoryHEALTHCARE = 'Predicted: Category=HEALTHCARE' ;
label P_CategoryFITNESS = 'Predicted: Category=FITNESS' ;
label P_CategoryOTHER = 'Predicted: Category=OTHER' ;
label P_CategorySALES = 'Predicted: Category=SALES' ;
label P_CategoryCONSULTANT = 'Predicted: Category=CONSULTANT' ;
label P_CategoryDIGITAL_MEDIA = 'Predicted: Category=DIGITAL-MEDIA' ;
label Q_CategoryHR = 'Unadjusted P: Category=HR' ;
label Q_CategoryDESIGNER = 'Unadjusted P: Category=DESIGNER' ;
label Q_CategoryINFORMATION_TECHNOLOGY = 
'Unadjusted P: Category=INFORMATION-TECHNOLOGY' ;
label Q_CategoryTEACHER = 'Unadjusted P: Category=TEACHER' ;
label Q_CategoryADVOCATE = 'Unadjusted P: Category=ADVOCATE' ;
label Q_CategoryBUSINESS_DEVELOPMENT = 
'Unadjusted P: Category=BUSINESS-DEVELOPMENT' ;
label Q_CategoryHEALTHCARE = 'Unadjusted P: Category=HEALTHCARE' ;
label Q_CategoryFITNESS = 'Unadjusted P: Category=FITNESS' ;
label Q_CategoryOTHER = 'Unadjusted P: Category=OTHER' ;
label Q_CategorySALES = 'Unadjusted P: Category=SALES' ;
label Q_CategoryCONSULTANT = 'Unadjusted P: Category=CONSULTANT' ;
label Q_CategoryDIGITAL_MEDIA = 'Unadjusted P: Category=DIGITAL-MEDIA' ;
label V_CategoryHR = 'Validated: Category=HR' ;
label V_CategoryDESIGNER = 'Validated: Category=DESIGNER' ;
label V_CategoryINFORMATION_TECHNOLOGY = 
'Validated: Category=INFORMATION-TECHNOLOGY' ;
label V_CategoryTEACHER = 'Validated: Category=TEACHER' ;
label V_CategoryADVOCATE = 'Validated: Category=ADVOCATE' ;
label V_CategoryBUSINESS_DEVELOPMENT = 
'Validated: Category=BUSINESS-DEVELOPMENT' ;
label V_CategoryHEALTHCARE = 'Validated: Category=HEALTHCARE' ;
label V_CategoryFITNESS = 'Validated: Category=FITNESS' ;
label V_CategoryOTHER = 'Validated: Category=OTHER' ;
label V_CategorySALES = 'Validated: Category=SALES' ;
label V_CategoryCONSULTANT = 'Validated: Category=CONSULTANT' ;
label V_CategoryDIGITAL_MEDIA = 'Validated: Category=DIGITAL-MEDIA' ;
label I_Category = 'Into: Category' ;
label U_Category = 'Unnormalized Into: Category' ;
label _WARN_ = 'Warnings' ;


******      TEMPORARY VARIABLES FOR FORMATTED VALUES      ******;
LENGTH _ARBFMT_22 $     22; DROP _ARBFMT_22; 
_ARBFMT_22 = ' '; /* Initialize to avoid warning. */


******             ASSIGN OBSERVATION TO NODE             ******;
IF  NOT MISSING(TextCluster10_SVD4 ) AND 
  TextCluster10_SVD4  <     -0.3566006636464 THEN DO;
  _NODE_  =                    2;
  _LEAF_  =                    1;
  P_CategoryHR  =      0.9090909090909;
  P_CategoryDESIGNER  =                    0;
  P_CategoryINFORMATION_TECHNOLOGY  =                    0;
  P_CategoryTEACHER  =                    0;
  P_CategoryADVOCATE  =     0.04545454545454;
  P_CategoryBUSINESS_DEVELOPMENT  =                    0;
  P_CategoryHEALTHCARE  =     0.02272727272727;
  P_CategoryFITNESS  =     0.02272727272727;
  P_CategoryOTHER  =                    0;
  P_CategorySALES  =                    0;
  P_CategoryCONSULTANT  =                    0;
  P_CategoryDIGITAL_MEDIA  =                    0;
  Q_CategoryHR  =      0.9090909090909;
  Q_CategoryDESIGNER  =                    0;
  Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
  Q_CategoryTEACHER  =                    0;
  Q_CategoryADVOCATE  =     0.04545454545454;
  Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
  Q_CategoryHEALTHCARE  =     0.02272727272727;
  Q_CategoryFITNESS  =     0.02272727272727;
  Q_CategoryOTHER  =                    0;
  Q_CategorySALES  =                    0;
  Q_CategoryCONSULTANT  =                    0;
  Q_CategoryDIGITAL_MEDIA  =                    0;
  V_CategoryHR  =                0.875;
  V_CategoryDESIGNER  =                    0;
  V_CategoryINFORMATION_TECHNOLOGY  =                    0;
  V_CategoryTEACHER  =                    0;
  V_CategoryADVOCATE  =                    0;
  V_CategoryBUSINESS_DEVELOPMENT  =                    0;
  V_CategoryHEALTHCARE  =     0.04166666666666;
  V_CategoryFITNESS  =                    0;
  V_CategoryOTHER  =                    0;
  V_CategorySALES  =                    0;
  V_CategoryCONSULTANT  =     0.08333333333333;
  V_CategoryDIGITAL_MEDIA  =                    0;
  I_Category  = 'HR' ;
  U_Category  = 'HR' ;
  END;
ELSE DO;
  IF  NOT MISSING(TextCluster10_SVD5 ) AND 
    TextCluster10_SVD5  <    -0.30020685125388 THEN DO;
    _NODE_  =                    4;
    _LEAF_  =                    2;
    P_CategoryHR  =                    0;
    P_CategoryDESIGNER  =     0.02222222222222;
    P_CategoryINFORMATION_TECHNOLOGY  =                    0;
    P_CategoryTEACHER  =     0.77777777777777;
    P_CategoryADVOCATE  =     0.08888888888888;
    P_CategoryBUSINESS_DEVELOPMENT  =                    0;
    P_CategoryHEALTHCARE  =     0.02222222222222;
    P_CategoryFITNESS  =     0.08888888888888;
    P_CategoryOTHER  =                    0;
    P_CategorySALES  =                    0;
    P_CategoryCONSULTANT  =                    0;
    P_CategoryDIGITAL_MEDIA  =                    0;
    Q_CategoryHR  =                    0;
    Q_CategoryDESIGNER  =     0.02222222222222;
    Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
    Q_CategoryTEACHER  =     0.77777777777777;
    Q_CategoryADVOCATE  =     0.08888888888888;
    Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
    Q_CategoryHEALTHCARE  =     0.02222222222222;
    Q_CategoryFITNESS  =     0.08888888888888;
    Q_CategoryOTHER  =                    0;
    Q_CategorySALES  =                    0;
    Q_CategoryCONSULTANT  =                    0;
    Q_CategoryDIGITAL_MEDIA  =                    0;
    V_CategoryHR  =     0.02631578947368;
    V_CategoryDESIGNER  =     0.05263157894736;
    V_CategoryINFORMATION_TECHNOLOGY  =                    0;
    V_CategoryTEACHER  =     0.60526315789473;
    V_CategoryADVOCATE  =     0.07894736842105;
    V_CategoryBUSINESS_DEVELOPMENT  =                    0;
    V_CategoryHEALTHCARE  =                    0;
    V_CategoryFITNESS  =     0.07894736842105;
    V_CategoryOTHER  =      0.1578947368421;
    V_CategorySALES  =                    0;
    V_CategoryCONSULTANT  =                    0;
    V_CategoryDIGITAL_MEDIA  =                    0;
    I_Category  = 'TEACHER' ;
    U_Category  = 'TEACHER' ;
    END;
  ELSE DO;
    IF  NOT MISSING(TextCluster10_SVD2 ) AND 
          0.28330980301825 <= TextCluster10_SVD2  THEN DO;
      _NODE_  =                    9;
      _LEAF_  =                   10;
      P_CategoryHR  =                    0;
      P_CategoryDESIGNER  =     0.02325581395348;
      P_CategoryINFORMATION_TECHNOLOGY  =     0.54651162790697;
      P_CategoryTEACHER  =                    0;
      P_CategoryADVOCATE  =     0.02325581395348;
      P_CategoryBUSINESS_DEVELOPMENT  =                    0;
      P_CategoryHEALTHCARE  =     0.03488372093023;
      P_CategoryFITNESS  =                    0;
      P_CategoryOTHER  =     0.05813953488372;
      P_CategorySALES  =                    0;
      P_CategoryCONSULTANT  =     0.24418604651162;
      P_CategoryDIGITAL_MEDIA  =     0.06976744186046;
      Q_CategoryHR  =                    0;
      Q_CategoryDESIGNER  =     0.02325581395348;
      Q_CategoryINFORMATION_TECHNOLOGY  =     0.54651162790697;
      Q_CategoryTEACHER  =                    0;
      Q_CategoryADVOCATE  =     0.02325581395348;
      Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
      Q_CategoryHEALTHCARE  =     0.03488372093023;
      Q_CategoryFITNESS  =                    0;
      Q_CategoryOTHER  =     0.05813953488372;
      Q_CategorySALES  =                    0;
      Q_CategoryCONSULTANT  =     0.24418604651162;
      Q_CategoryDIGITAL_MEDIA  =     0.06976744186046;
      V_CategoryHR  =                    0;
      V_CategoryDESIGNER  =     0.03846153846153;
      V_CategoryINFORMATION_TECHNOLOGY  =      0.5576923076923;
      V_CategoryTEACHER  =                    0;
      V_CategoryADVOCATE  =     0.01923076923076;
      V_CategoryBUSINESS_DEVELOPMENT  =     0.01923076923076;
      V_CategoryHEALTHCARE  =     0.01923076923076;
      V_CategoryFITNESS  =                    0;
      V_CategoryOTHER  =      0.0576923076923;
      V_CategorySALES  =     0.01923076923076;
      V_CategoryCONSULTANT  =     0.17307692307692;
      V_CategoryDIGITAL_MEDIA  =     0.09615384615384;
      I_Category  = 'INFORMATION-TECHNOLOGY' ;
      U_Category  = 'INFORMATION-TECHNOLOGY' ;
      END;
    ELSE DO;
      IF  NOT MISSING(TextCluster10_SVD6 ) AND 
        TextCluster10_SVD6  <    -0.18416908989601 THEN DO;
        IF  NOT MISSING(TextCluster10_SVD4 ) AND 
          TextCluster10_SVD4  <     0.03257710277888 THEN DO;
          _NODE_  =                   14;
          _LEAF_  =                    3;
          P_CategoryHR  =                  0.4;
          P_CategoryDESIGNER  =                    0;
          P_CategoryINFORMATION_TECHNOLOGY  =                    0;
          P_CategoryTEACHER  =                    0;
          P_CategoryADVOCATE  =                    0;
          P_CategoryBUSINESS_DEVELOPMENT  =                  0.2;
          P_CategoryHEALTHCARE  =                  0.2;
          P_CategoryFITNESS  =                    0;
          P_CategoryOTHER  =                    0;
          P_CategorySALES  =                    0;
          P_CategoryCONSULTANT  =                  0.2;
          P_CategoryDIGITAL_MEDIA  =                    0;
          Q_CategoryHR  =                  0.4;
          Q_CategoryDESIGNER  =                    0;
          Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
          Q_CategoryTEACHER  =                    0;
          Q_CategoryADVOCATE  =                    0;
          Q_CategoryBUSINESS_DEVELOPMENT  =                  0.2;
          Q_CategoryHEALTHCARE  =                  0.2;
          Q_CategoryFITNESS  =                    0;
          Q_CategoryOTHER  =                    0;
          Q_CategorySALES  =                    0;
          Q_CategoryCONSULTANT  =                  0.2;
          Q_CategoryDIGITAL_MEDIA  =                    0;
          V_CategoryHR  =                    0;
          V_CategoryDESIGNER  =                    0;
          V_CategoryINFORMATION_TECHNOLOGY  =                  0.5;
          V_CategoryTEACHER  =                    0;
          V_CategoryADVOCATE  =                    0;
          V_CategoryBUSINESS_DEVELOPMENT  =                    0;
          V_CategoryHEALTHCARE  =                    0;
          V_CategoryFITNESS  =                    0;
          V_CategoryOTHER  =                  0.5;
          V_CategorySALES  =                    0;
          V_CategoryCONSULTANT  =                    0;
          V_CategoryDIGITAL_MEDIA  =                    0;
          I_Category  = 'HR' ;
          U_Category  = 'HR' ;
          END;
        ELSE DO;
          IF  NOT MISSING(TextCluster10_SVD10 ) AND 
            TextCluster10_SVD10  <    -0.07870817493434 THEN DO;
            _NODE_  =                   18;
            _LEAF_  =                    4;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =                    0;
            P_CategoryINFORMATION_TECHNOLOGY  =                    0;
            P_CategoryTEACHER  =                    0;
            P_CategoryADVOCATE  =                    0;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =                    0;
            P_CategoryOTHER  =                    0;
            P_CategorySALES  =                    0;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =                    1;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =                    0;
            Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
            Q_CategoryTEACHER  =                    0;
            Q_CategoryADVOCATE  =                    0;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =                    0;
            Q_CategoryOTHER  =                    0;
            Q_CategorySALES  =                    0;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =                    1;
            V_CategoryHR  =                    0;
            V_CategoryDESIGNER  =                    0;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =                    0;
            V_CategoryADVOCATE  =                    0;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =                    0;
            V_CategoryFITNESS  =                    0;
            V_CategoryOTHER  =                    0;
            V_CategorySALES  =                    0;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =                    1;
            I_Category  = 'DIGITAL-MEDIA' ;
            U_Category  = 'DIGITAL-MEDIA' ;
            END;
          ELSE DO;
            _NODE_  =                   19;
            _LEAF_  =                    5;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =     0.86046511627906;
            P_CategoryINFORMATION_TECHNOLOGY  =                    0;
            P_CategoryTEACHER  =                    0;
            P_CategoryADVOCATE  =                    0;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =                    0;
            P_CategoryOTHER  =     0.02325581395348;
            P_CategorySALES  =     0.04651162790697;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =     0.06976744186046;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =     0.86046511627906;
            Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
            Q_CategoryTEACHER  =                    0;
            Q_CategoryADVOCATE  =                    0;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =                    0;
            Q_CategoryOTHER  =     0.02325581395348;
            Q_CategorySALES  =     0.04651162790697;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =     0.06976744186046;
            V_CategoryHR  =     0.03333333333333;
            V_CategoryDESIGNER  =     0.66666666666666;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =     0.03333333333333;
            V_CategoryADVOCATE  =                    0;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =                    0;
            V_CategoryFITNESS  =     0.03333333333333;
            V_CategoryOTHER  =                    0;
            V_CategorySALES  =     0.06666666666666;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =     0.16666666666666;
            I_Category  = 'DESIGNER' ;
            U_Category  = 'DESIGNER' ;
            END;
          END;
        END;
      ELSE DO;
        IF  NOT MISSING(TextCluster10_SVD12 ) AND 
          TextCluster10_SVD12  <    -0.12604842708992 THEN DO;
          IF  NOT MISSING(TextCluster10_SVD6 ) AND 
            TextCluster10_SVD6  <    -0.02385570691405 THEN DO;
            _NODE_  =                   20;
            _LEAF_  =                    6;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =                 0.25;
            P_CategoryINFORMATION_TECHNOLOGY  =                0.125;
            P_CategoryTEACHER  =                    0;
            P_CategoryADVOCATE  =                0.125;
            P_CategoryBUSINESS_DEVELOPMENT  =                0.125;
            P_CategoryHEALTHCARE  =                0.125;
            P_CategoryFITNESS  =                0.125;
            P_CategoryOTHER  =                    0;
            P_CategorySALES  =                    0;
            P_CategoryCONSULTANT  =                0.125;
            P_CategoryDIGITAL_MEDIA  =                    0;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =                 0.25;
            Q_CategoryINFORMATION_TECHNOLOGY  =                0.125;
            Q_CategoryTEACHER  =                    0;
            Q_CategoryADVOCATE  =                0.125;
            Q_CategoryBUSINESS_DEVELOPMENT  =                0.125;
            Q_CategoryHEALTHCARE  =                0.125;
            Q_CategoryFITNESS  =                0.125;
            Q_CategoryOTHER  =                    0;
            Q_CategorySALES  =                    0;
            Q_CategoryCONSULTANT  =                0.125;
            Q_CategoryDIGITAL_MEDIA  =                    0;
            V_CategoryHR  =                    0;
            V_CategoryDESIGNER  =                  0.5;
            V_CategoryINFORMATION_TECHNOLOGY  =                  0.5;
            V_CategoryTEACHER  =                    0;
            V_CategoryADVOCATE  =                    0;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =                    0;
            V_CategoryFITNESS  =                    0;
            V_CategoryOTHER  =                    0;
            V_CategorySALES  =                    0;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =                    0;
            I_Category  = 'DESIGNER' ;
            U_Category  = 'DESIGNER' ;
            END;
          ELSE DO;
            _NODE_  =                   21;
            _LEAF_  =                    7;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =                    0;
            P_CategoryINFORMATION_TECHNOLOGY  =                    0;
            P_CategoryTEACHER  =                    0;
            P_CategoryADVOCATE  =     0.19148936170212;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =     0.74468085106382;
            P_CategoryOTHER  =     0.06382978723404;
            P_CategorySALES  =                    0;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =                    0;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =                    0;
            Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
            Q_CategoryTEACHER  =                    0;
            Q_CategoryADVOCATE  =     0.19148936170212;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =     0.74468085106382;
            Q_CategoryOTHER  =     0.06382978723404;
            Q_CategorySALES  =                    0;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =                    0;
            V_CategoryHR  =                    0;
            V_CategoryDESIGNER  =                    0;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =                    0;
            V_CategoryADVOCATE  =                    0;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =     0.05555555555555;
            V_CategoryFITNESS  =     0.88888888888888;
            V_CategoryOTHER  =     0.05555555555555;
            V_CategorySALES  =                    0;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =                    0;
            I_Category  = 'FITNESS' ;
            U_Category  = 'FITNESS' ;
            END;
          END;
        ELSE DO;
          IF  NOT MISSING(TextCluster10_SVD4 ) AND 
                0.28778989493305 <= TextCluster10_SVD4  THEN DO;
            _NODE_  =                   23;
            _LEAF_  =                    9;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =     0.16666666666666;
            P_CategoryINFORMATION_TECHNOLOGY  =     0.08333333333333;
            P_CategoryTEACHER  =     0.66666666666666;
            P_CategoryADVOCATE  =                    0;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =                    0;
            P_CategoryOTHER  =                    0;
            P_CategorySALES  =                    0;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =     0.08333333333333;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =     0.16666666666666;
            Q_CategoryINFORMATION_TECHNOLOGY  =     0.08333333333333;
            Q_CategoryTEACHER  =     0.66666666666666;
            Q_CategoryADVOCATE  =                    0;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =                    0;
            Q_CategoryOTHER  =                    0;
            Q_CategorySALES  =                    0;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =     0.08333333333333;
            V_CategoryHR  =                    0;
            V_CategoryDESIGNER  =                    0;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =                  0.5;
            V_CategoryADVOCATE  =                 0.25;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =                    0;
            V_CategoryFITNESS  =                    0;
            V_CategoryOTHER  =                 0.25;
            V_CategorySALES  =                    0;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =                    0;
            I_Category  = 'TEACHER' ;
            U_Category  = 'TEACHER' ;
            END;
          ELSE DO;
            _NODE_  =                   22;
            _LEAF_  =                    8;
            P_CategoryHR  =     0.03475935828877;
            P_CategoryDESIGNER  =     0.02406417112299;
            P_CategoryINFORMATION_TECHNOLOGY  =     0.02673796791443;
            P_CategoryTEACHER  =      0.0187165775401;
            P_CategoryADVOCATE  =     0.10427807486631;
            P_CategoryBUSINESS_DEVELOPMENT  =     0.15508021390374;
            P_CategoryHEALTHCARE  =     0.13368983957219;
            P_CategoryFITNESS  =     0.04545454545454;
            P_CategoryOTHER  =     0.14438502673796;
            P_CategorySALES  =     0.14973262032085;
            P_CategoryCONSULTANT  =     0.09090909090909;
            P_CategoryDIGITAL_MEDIA  =     0.07219251336898;
            Q_CategoryHR  =     0.03475935828877;
            Q_CategoryDESIGNER  =     0.02406417112299;
            Q_CategoryINFORMATION_TECHNOLOGY  =     0.02673796791443;
            Q_CategoryTEACHER  =      0.0187165775401;
            Q_CategoryADVOCATE  =     0.10427807486631;
            Q_CategoryBUSINESS_DEVELOPMENT  =     0.15508021390374;
            Q_CategoryHEALTHCARE  =     0.13368983957219;
            Q_CategoryFITNESS  =     0.04545454545454;
            Q_CategoryOTHER  =     0.14438502673796;
            Q_CategorySALES  =     0.14973262032085;
            Q_CategoryCONSULTANT  =     0.09090909090909;
            Q_CategoryDIGITAL_MEDIA  =     0.07219251336898;
            V_CategoryHR  =     0.03896103896103;
            V_CategoryDESIGNER  =     0.02597402597402;
            V_CategoryINFORMATION_TECHNOLOGY  =     0.02164502164502;
            V_CategoryTEACHER  =     0.02164502164502;
            V_CategoryADVOCATE  =     0.12987012987012;
            V_CategoryBUSINESS_DEVELOPMENT  =     0.15151515151515;
            V_CategoryHEALTHCARE  =     0.12987012987012;
            V_CategoryFITNESS  =     0.06493506493506;
            V_CategoryOTHER  =     0.11255411255411;
            V_CategorySALES  =     0.13419913419913;
            V_CategoryCONSULTANT  =      0.1038961038961;
            V_CategoryDIGITAL_MEDIA  =     0.06493506493506;
            I_Category  = 'BUSINESS-DEVELOPMENT' ;
            U_Category  = 'BUSINESS-DEVELOPMENT' ;
            END;
          END;
        END;
      END;
    END;
  END;

****************************************************************;
******          END OF DECISION TREE SCORING CODE         ******;
****************************************************************;

