if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER10_SVD10'
'TEXTCLUSTER10_SVD12'
'TEXTCLUSTER10_SVD15'
'TEXTCLUSTER10_SVD2'
'TEXTCLUSTER10_SVD25'
'TEXTCLUSTER10_SVD3'
'TEXTCLUSTER10_SVD4'
'TEXTCLUSTER10_SVD5'
'TEXTCLUSTER10_SVD6'
'TEXTCLUSTER10_SVD7'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg3: Rejected using stepwise selection";
end;
end;
