if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER5_SVD10'
'TEXTCLUSTER5_SVD12'
'TEXTCLUSTER5_SVD15'
'TEXTCLUSTER5_SVD2'
'TEXTCLUSTER5_SVD25'
'TEXTCLUSTER5_SVD3'
'TEXTCLUSTER5_SVD4'
'TEXTCLUSTER5_SVD5'
'TEXTCLUSTER5_SVD6'
'TEXTCLUSTER5_SVD7'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg2: Rejected using stepwise selection";
end;
end;
