if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'TEXTCLUSTER11_SVD2'
'TEXTCLUSTER11_SVD22'
'TEXTCLUSTER11_SVD3'
'TEXTCLUSTER11_SVD4'
'TEXTCLUSTER11_SVD5'
'TEXTCLUSTER11_SVD7'
'TEXTCLUSTER11_SVD8'
'TEXTCLUSTER11_SVD9'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg7: Rejected using stepwise selection";
end;
end;
