****************************************************************;
******             DECISION TREE SCORING CODE             ******;
****************************************************************;

******         LENGTHS OF NEW CHARACTER VARIABLES         ******;
LENGTH F_Category  $   22; 
LENGTH I_Category  $   22; 
LENGTH U_Category  $   22; 
LENGTH _WARN_  $    4; 

******              LABELS FOR NEW VARIABLES              ******;
label _NODE_ = 'Node' ;
label _LEAF_ = 'Leaf' ;
label P_CategoryHR = 'Predicted: Category=HR' ;
label P_CategoryDESIGNER = 'Predicted: Category=DESIGNER' ;
label P_CategoryINFORMATION_TECHNOLOGY = 
'Predicted: Category=INFORMATION-TECHNOLOGY' ;
label P_CategoryTEACHER = 'Predicted: Category=TEACHER' ;
label P_CategoryADVOCATE = 'Predicted: Category=ADVOCATE' ;
label P_CategoryBUSINESS_DEVELOPMENT = 
'Predicted: Category=BUSINESS-DEVELOPMENT' ;
label P_CategoryHEALTHCARE = 'Predicted: Category=HEALTHCARE' ;
label P_CategoryFITNESS = 'Predicted: Category=FITNESS' ;
label P_CategoryOTHER = 'Predicted: Category=OTHER' ;
label P_CategorySALES = 'Predicted: Category=SALES' ;
label P_CategoryCONSULTANT = 'Predicted: Category=CONSULTANT' ;
label P_CategoryDIGITAL_MEDIA = 'Predicted: Category=DIGITAL-MEDIA' ;
label Q_CategoryHR = 'Unadjusted P: Category=HR' ;
label Q_CategoryDESIGNER = 'Unadjusted P: Category=DESIGNER' ;
label Q_CategoryINFORMATION_TECHNOLOGY = 
'Unadjusted P: Category=INFORMATION-TECHNOLOGY' ;
label Q_CategoryTEACHER = 'Unadjusted P: Category=TEACHER' ;
label Q_CategoryADVOCATE = 'Unadjusted P: Category=ADVOCATE' ;
label Q_CategoryBUSINESS_DEVELOPMENT = 
'Unadjusted P: Category=BUSINESS-DEVELOPMENT' ;
label Q_CategoryHEALTHCARE = 'Unadjusted P: Category=HEALTHCARE' ;
label Q_CategoryFITNESS = 'Unadjusted P: Category=FITNESS' ;
label Q_CategoryOTHER = 'Unadjusted P: Category=OTHER' ;
label Q_CategorySALES = 'Unadjusted P: Category=SALES' ;
label Q_CategoryCONSULTANT = 'Unadjusted P: Category=CONSULTANT' ;
label Q_CategoryDIGITAL_MEDIA = 'Unadjusted P: Category=DIGITAL-MEDIA' ;
label V_CategoryHR = 'Validated: Category=HR' ;
label V_CategoryDESIGNER = 'Validated: Category=DESIGNER' ;
label V_CategoryINFORMATION_TECHNOLOGY = 
'Validated: Category=INFORMATION-TECHNOLOGY' ;
label V_CategoryTEACHER = 'Validated: Category=TEACHER' ;
label V_CategoryADVOCATE = 'Validated: Category=ADVOCATE' ;
label V_CategoryBUSINESS_DEVELOPMENT = 
'Validated: Category=BUSINESS-DEVELOPMENT' ;
label V_CategoryHEALTHCARE = 'Validated: Category=HEALTHCARE' ;
label V_CategoryFITNESS = 'Validated: Category=FITNESS' ;
label V_CategoryOTHER = 'Validated: Category=OTHER' ;
label V_CategorySALES = 'Validated: Category=SALES' ;
label V_CategoryCONSULTANT = 'Validated: Category=CONSULTANT' ;
label V_CategoryDIGITAL_MEDIA = 'Validated: Category=DIGITAL-MEDIA' ;
label R_CategoryHR = 'Residual: Category=HR' ;
label R_CategoryDESIGNER = 'Residual: Category=DESIGNER' ;
label R_CategoryINFORMATION_TECHNOLOGY = 
'Residual: Category=INFORMATION-TECHNOLOGY' ;
label R_CategoryTEACHER = 'Residual: Category=TEACHER' ;
label R_CategoryADVOCATE = 'Residual: Category=ADVOCATE' ;
label R_CategoryBUSINESS_DEVELOPMENT = 
'Residual: Category=BUSINESS-DEVELOPMENT' ;
label R_CategoryHEALTHCARE = 'Residual: Category=HEALTHCARE' ;
label R_CategoryFITNESS = 'Residual: Category=FITNESS' ;
label R_CategoryOTHER = 'Residual: Category=OTHER' ;
label R_CategorySALES = 'Residual: Category=SALES' ;
label R_CategoryCONSULTANT = 'Residual: Category=CONSULTANT' ;
label R_CategoryDIGITAL_MEDIA = 'Residual: Category=DIGITAL-MEDIA' ;
label F_Category = 'From: Category' ;
label I_Category = 'Into: Category' ;
label U_Category = 'Unnormalized Into: Category' ;
label _WARN_ = 'Warnings' ;


******      TEMPORARY VARIABLES FOR FORMATTED VALUES      ******;
LENGTH _ARBFMT_22 $     22; DROP _ARBFMT_22; 
_ARBFMT_22 = ' '; /* Initialize to avoid warning. */


_ARBFMT_22 = PUT( Category , $22.);
 %DMNORMCP( _ARBFMT_22, F_Category );

******             ASSIGN OBSERVATION TO NODE             ******;
IF  NOT MISSING(TextCluster4_SVD4 ) AND 
  TextCluster4_SVD4  <    -0.22159654602699 THEN DO;
  _NODE_  =                    2;
  _LEAF_  =                    1;
  P_CategoryHR  =     0.80701754385964;
  P_CategoryDESIGNER  =                    0;
  P_CategoryINFORMATION_TECHNOLOGY  =                    0;
  P_CategoryTEACHER  =                    0;
  P_CategoryADVOCATE  =     0.05263157894736;
  P_CategoryBUSINESS_DEVELOPMENT  =     0.01754385964912;
  P_CategoryHEALTHCARE  =     0.05263157894736;
  P_CategoryFITNESS  =     0.01754385964912;
  P_CategoryOTHER  =     0.01754385964912;
  P_CategorySALES  =     0.01754385964912;
  P_CategoryCONSULTANT  =     0.01754385964912;
  P_CategoryDIGITAL_MEDIA  =                    0;
  Q_CategoryHR  =     0.80701754385964;
  Q_CategoryDESIGNER  =                    0;
  Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
  Q_CategoryTEACHER  =                    0;
  Q_CategoryADVOCATE  =     0.05263157894736;
  Q_CategoryBUSINESS_DEVELOPMENT  =     0.01754385964912;
  Q_CategoryHEALTHCARE  =     0.05263157894736;
  Q_CategoryFITNESS  =     0.01754385964912;
  Q_CategoryOTHER  =     0.01754385964912;
  Q_CategorySALES  =     0.01754385964912;
  Q_CategoryCONSULTANT  =     0.01754385964912;
  Q_CategoryDIGITAL_MEDIA  =                    0;
  V_CategoryHR  =     0.71052631578947;
  V_CategoryDESIGNER  =                    0;
  V_CategoryINFORMATION_TECHNOLOGY  =     0.05263157894736;
  V_CategoryTEACHER  =                    0;
  V_CategoryADVOCATE  =     0.02631578947368;
  V_CategoryBUSINESS_DEVELOPMENT  =     0.02631578947368;
  V_CategoryHEALTHCARE  =     0.07894736842105;
  V_CategoryFITNESS  =     0.02631578947368;
  V_CategoryOTHER  =     0.02631578947368;
  V_CategorySALES  =                    0;
  V_CategoryCONSULTANT  =     0.05263157894736;
  V_CategoryDIGITAL_MEDIA  =                    0;
  I_Category  = 'HR' ;
  U_Category  = 'HR' ;
  END;
ELSE DO;
  IF  NOT MISSING(TextCluster4_SVD5 ) AND 
    TextCluster4_SVD5  <    -0.25539876415752 THEN DO;
    _NODE_  =                    6;
    _LEAF_  =                    2;
    P_CategoryHR  =                    0;
    P_CategoryDESIGNER  =                 0.02;
    P_CategoryINFORMATION_TECHNOLOGY  =                    0;
    P_CategoryTEACHER  =                 0.74;
    P_CategoryADVOCATE  =                  0.1;
    P_CategoryBUSINESS_DEVELOPMENT  =                    0;
    P_CategoryHEALTHCARE  =                 0.02;
    P_CategoryFITNESS  =                 0.12;
    P_CategoryOTHER  =                    0;
    P_CategorySALES  =                    0;
    P_CategoryCONSULTANT  =                    0;
    P_CategoryDIGITAL_MEDIA  =                    0;
    Q_CategoryHR  =                    0;
    Q_CategoryDESIGNER  =                 0.02;
    Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
    Q_CategoryTEACHER  =                 0.74;
    Q_CategoryADVOCATE  =                  0.1;
    Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
    Q_CategoryHEALTHCARE  =                 0.02;
    Q_CategoryFITNESS  =                 0.12;
    Q_CategoryOTHER  =                    0;
    Q_CategorySALES  =                    0;
    Q_CategoryCONSULTANT  =                    0;
    Q_CategoryDIGITAL_MEDIA  =                    0;
    V_CategoryHR  =     0.02272727272727;
    V_CategoryDESIGNER  =     0.04545454545454;
    V_CategoryINFORMATION_TECHNOLOGY  =                    0;
    V_CategoryTEACHER  =     0.52272727272727;
    V_CategoryADVOCATE  =     0.06818181818181;
    V_CategoryBUSINESS_DEVELOPMENT  =                    0;
    V_CategoryHEALTHCARE  =     0.04545454545454;
    V_CategoryFITNESS  =     0.09090909090909;
    V_CategoryOTHER  =     0.18181818181818;
    V_CategorySALES  =                    0;
    V_CategoryCONSULTANT  =     0.02272727272727;
    V_CategoryDIGITAL_MEDIA  =                    0;
    I_Category  = 'TEACHER' ;
    U_Category  = 'TEACHER' ;
    END;
  ELSE DO;
    IF  NOT MISSING(TextCluster4_SVD2 ) AND 
          0.22199140753138 <= TextCluster4_SVD2  THEN DO;
      _NODE_  =                   13;
      _LEAF_  =                    9;
      P_CategoryHR  =                    0;
      P_CategoryDESIGNER  =              0.03125;
      P_CategoryINFORMATION_TECHNOLOGY  =     0.52083333333333;
      P_CategoryTEACHER  =                    0;
      P_CategoryADVOCATE  =     0.02083333333333;
      P_CategoryBUSINESS_DEVELOPMENT  =     0.02083333333333;
      P_CategoryHEALTHCARE  =              0.03125;
      P_CategoryFITNESS  =                    0;
      P_CategoryOTHER  =     0.08333333333333;
      P_CategorySALES  =                    0;
      P_CategoryCONSULTANT  =              0.21875;
      P_CategoryDIGITAL_MEDIA  =     0.07291666666666;
      Q_CategoryHR  =                    0;
      Q_CategoryDESIGNER  =              0.03125;
      Q_CategoryINFORMATION_TECHNOLOGY  =     0.52083333333333;
      Q_CategoryTEACHER  =                    0;
      Q_CategoryADVOCATE  =     0.02083333333333;
      Q_CategoryBUSINESS_DEVELOPMENT  =     0.02083333333333;
      Q_CategoryHEALTHCARE  =              0.03125;
      Q_CategoryFITNESS  =                    0;
      Q_CategoryOTHER  =     0.08333333333333;
      Q_CategorySALES  =                    0;
      Q_CategoryCONSULTANT  =              0.21875;
      Q_CategoryDIGITAL_MEDIA  =     0.07291666666666;
      V_CategoryHR  =                    0;
      V_CategoryDESIGNER  =     0.05357142857142;
      V_CategoryINFORMATION_TECHNOLOGY  =     0.51785714285714;
      V_CategoryTEACHER  =                    0;
      V_CategoryADVOCATE  =     0.01785714285714;
      V_CategoryBUSINESS_DEVELOPMENT  =     0.05357142857142;
      V_CategoryHEALTHCARE  =     0.01785714285714;
      V_CategoryFITNESS  =                    0;
      V_CategoryOTHER  =     0.05357142857142;
      V_CategorySALES  =     0.01785714285714;
      V_CategoryCONSULTANT  =     0.16071428571428;
      V_CategoryDIGITAL_MEDIA  =     0.10714285714285;
      I_Category  = 'INFORMATION-TECHNOLOGY' ;
      U_Category  = 'INFORMATION-TECHNOLOGY' ;
      END;
    ELSE DO;
      IF  NOT MISSING(TextCluster4_SVD6 ) AND 
        TextCluster4_SVD6  <    -0.15676518608919 THEN DO;
        IF  NOT MISSING(TextCluster4_SVD4 ) AND 
          TextCluster4_SVD4  <     0.03519855095692 THEN DO;
          _NODE_  =                   20;
          _LEAF_  =                    3;
          P_CategoryHR  =                  0.4;
          P_CategoryDESIGNER  =                    0;
          P_CategoryINFORMATION_TECHNOLOGY  =                    0;
          P_CategoryTEACHER  =                    0;
          P_CategoryADVOCATE  =                    0;
          P_CategoryBUSINESS_DEVELOPMENT  =                  0.2;
          P_CategoryHEALTHCARE  =                  0.2;
          P_CategoryFITNESS  =                    0;
          P_CategoryOTHER  =                    0;
          P_CategorySALES  =                    0;
          P_CategoryCONSULTANT  =                  0.2;
          P_CategoryDIGITAL_MEDIA  =                    0;
          Q_CategoryHR  =                  0.4;
          Q_CategoryDESIGNER  =                    0;
          Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
          Q_CategoryTEACHER  =                    0;
          Q_CategoryADVOCATE  =                    0;
          Q_CategoryBUSINESS_DEVELOPMENT  =                  0.2;
          Q_CategoryHEALTHCARE  =                  0.2;
          Q_CategoryFITNESS  =                    0;
          Q_CategoryOTHER  =                    0;
          Q_CategorySALES  =                    0;
          Q_CategoryCONSULTANT  =                  0.2;
          Q_CategoryDIGITAL_MEDIA  =                    0;
          V_CategoryHR  =                    0;
          V_CategoryDESIGNER  =                    1;
          V_CategoryINFORMATION_TECHNOLOGY  =                    0;
          V_CategoryTEACHER  =                    0;
          V_CategoryADVOCATE  =                    0;
          V_CategoryBUSINESS_DEVELOPMENT  =                    0;
          V_CategoryHEALTHCARE  =                    0;
          V_CategoryFITNESS  =                    0;
          V_CategoryOTHER  =                    0;
          V_CategorySALES  =                    0;
          V_CategoryCONSULTANT  =                    0;
          V_CategoryDIGITAL_MEDIA  =                    0;
          I_Category  = 'HR' ;
          U_Category  = 'HR' ;
          END;
        ELSE DO;
          IF  NOT MISSING(TextCluster4_SVD10 ) AND 
            TextCluster4_SVD10  <      0.0253142255519 THEN DO;
            _NODE_  =                   24;
            _LEAF_  =                    4;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =                    0;
            P_CategoryINFORMATION_TECHNOLOGY  =                    0;
            P_CategoryTEACHER  =                    0;
            P_CategoryADVOCATE  =                    0;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =                    0;
            P_CategoryOTHER  =                    0;
            P_CategorySALES  =                    0;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =                    1;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =                    0;
            Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
            Q_CategoryTEACHER  =                    0;
            Q_CategoryADVOCATE  =                    0;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =                    0;
            Q_CategoryOTHER  =                    0;
            Q_CategorySALES  =                    0;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =                    1;
            V_CategoryHR  =     0.09090909090909;
            V_CategoryDESIGNER  =     0.09090909090909;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =                    0;
            V_CategoryADVOCATE  =                    0;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =                    0;
            V_CategoryFITNESS  =     0.09090909090909;
            V_CategoryOTHER  =                    0;
            V_CategorySALES  =     0.09090909090909;
            V_CategoryCONSULTANT  =     0.09090909090909;
            V_CategoryDIGITAL_MEDIA  =     0.54545454545454;
            I_Category  = 'DIGITAL-MEDIA' ;
            U_Category  = 'DIGITAL-MEDIA' ;
            END;
          ELSE DO;
            _NODE_  =                   25;
            _LEAF_  =                    5;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =                  0.9;
            P_CategoryINFORMATION_TECHNOLOGY  =                    0;
            P_CategoryTEACHER  =                    0;
            P_CategoryADVOCATE  =                    0;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =                    0;
            P_CategoryOTHER  =                    0;
            P_CategorySALES  =                 0.05;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =                 0.05;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =                  0.9;
            Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
            Q_CategoryTEACHER  =                    0;
            Q_CategoryADVOCATE  =                    0;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =                    0;
            Q_CategoryOTHER  =                    0;
            Q_CategorySALES  =                 0.05;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =                 0.05;
            V_CategoryHR  =                    0;
            V_CategoryDESIGNER  =     0.78260869565217;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =     0.04347826086956;
            V_CategoryADVOCATE  =                    0;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =                    0;
            V_CategoryFITNESS  =                    0;
            V_CategoryOTHER  =                    0;
            V_CategorySALES  =     0.08695652173913;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =     0.08695652173913;
            I_Category  = 'DESIGNER' ;
            U_Category  = 'DESIGNER' ;
            END;
          END;
        END;
      ELSE DO;
        IF  NOT MISSING(TextCluster4_SVD12 ) AND 
          TextCluster4_SVD12  <    -0.11300450651431 THEN DO;
          _NODE_  =                   22;
          _LEAF_  =                    6;
          P_CategoryHR  =                    0;
          P_CategoryDESIGNER  =      0.0392156862745;
          P_CategoryINFORMATION_TECHNOLOGY  =                    0;
          P_CategoryTEACHER  =                    0;
          P_CategoryADVOCATE  =     0.17647058823529;
          P_CategoryBUSINESS_DEVELOPMENT  =     0.01960784313725;
          P_CategoryHEALTHCARE  =     0.01960784313725;
          P_CategoryFITNESS  =     0.66666666666666;
          P_CategoryOTHER  =     0.05882352941176;
          P_CategorySALES  =                    0;
          P_CategoryCONSULTANT  =     0.01960784313725;
          P_CategoryDIGITAL_MEDIA  =                    0;
          Q_CategoryHR  =                    0;
          Q_CategoryDESIGNER  =      0.0392156862745;
          Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
          Q_CategoryTEACHER  =                    0;
          Q_CategoryADVOCATE  =     0.17647058823529;
          Q_CategoryBUSINESS_DEVELOPMENT  =     0.01960784313725;
          Q_CategoryHEALTHCARE  =     0.01960784313725;
          Q_CategoryFITNESS  =     0.66666666666666;
          Q_CategoryOTHER  =     0.05882352941176;
          Q_CategorySALES  =                    0;
          Q_CategoryCONSULTANT  =     0.01960784313725;
          Q_CategoryDIGITAL_MEDIA  =                    0;
          V_CategoryHR  =                    0;
          V_CategoryDESIGNER  =                 0.05;
          V_CategoryINFORMATION_TECHNOLOGY  =                 0.05;
          V_CategoryTEACHER  =                    0;
          V_CategoryADVOCATE  =                    0;
          V_CategoryBUSINESS_DEVELOPMENT  =                    0;
          V_CategoryHEALTHCARE  =                 0.05;
          V_CategoryFITNESS  =                  0.8;
          V_CategoryOTHER  =                 0.05;
          V_CategorySALES  =                    0;
          V_CategoryCONSULTANT  =                    0;
          V_CategoryDIGITAL_MEDIA  =                    0;
          I_Category  = 'FITNESS' ;
          U_Category  = 'FITNESS' ;
          END;
        ELSE DO;
          IF  NOT MISSING(TextCluster4_SVD4 ) AND 
                0.26328465066599 <= TextCluster4_SVD4  THEN DO;
            _NODE_  =                   29;
            _LEAF_  =                    8;
            P_CategoryHR  =                    0;
            P_CategoryDESIGNER  =     0.22222222222222;
            P_CategoryINFORMATION_TECHNOLOGY  =                    0;
            P_CategoryTEACHER  =     0.66666666666666;
            P_CategoryADVOCATE  =                    0;
            P_CategoryBUSINESS_DEVELOPMENT  =                    0;
            P_CategoryHEALTHCARE  =                    0;
            P_CategoryFITNESS  =                    0;
            P_CategoryOTHER  =                    0;
            P_CategorySALES  =                    0;
            P_CategoryCONSULTANT  =                    0;
            P_CategoryDIGITAL_MEDIA  =     0.11111111111111;
            Q_CategoryHR  =                    0;
            Q_CategoryDESIGNER  =     0.22222222222222;
            Q_CategoryINFORMATION_TECHNOLOGY  =                    0;
            Q_CategoryTEACHER  =     0.66666666666666;
            Q_CategoryADVOCATE  =                    0;
            Q_CategoryBUSINESS_DEVELOPMENT  =                    0;
            Q_CategoryHEALTHCARE  =                    0;
            Q_CategoryFITNESS  =                    0;
            Q_CategoryOTHER  =                    0;
            Q_CategorySALES  =                    0;
            Q_CategoryCONSULTANT  =                    0;
            Q_CategoryDIGITAL_MEDIA  =     0.11111111111111;
            V_CategoryHR  =                    0;
            V_CategoryDESIGNER  =                    0;
            V_CategoryINFORMATION_TECHNOLOGY  =                    0;
            V_CategoryTEACHER  =     0.28571428571428;
            V_CategoryADVOCATE  =     0.28571428571428;
            V_CategoryBUSINESS_DEVELOPMENT  =                    0;
            V_CategoryHEALTHCARE  =     0.14285714285714;
            V_CategoryFITNESS  =                    0;
            V_CategoryOTHER  =                    0;
            V_CategorySALES  =     0.14285714285714;
            V_CategoryCONSULTANT  =                    0;
            V_CategoryDIGITAL_MEDIA  =     0.14285714285714;
            I_Category  = 'TEACHER' ;
            U_Category  = 'TEACHER' ;
            END;
          ELSE DO;
            _NODE_  =                   28;
            _LEAF_  =                    7;
            P_CategoryHR  =     0.01994301994301;
            P_CategoryDESIGNER  =     0.02564102564102;
            P_CategoryINFORMATION_TECHNOLOGY  =     0.02564102564102;
            P_CategoryTEACHER  =     0.01994301994301;
            P_CategoryADVOCATE  =      0.1082621082621;
            P_CategoryBUSINESS_DEVELOPMENT  =     0.15669515669515;
            P_CategoryHEALTHCARE  =     0.13675213675213;
            P_CategoryFITNESS  =     0.04843304843304;
            P_CategoryOTHER  =     0.14529914529914;
            P_CategorySALES  =     0.15669515669515;
            P_CategoryCONSULTANT  =     0.09401709401709;
            P_CategoryDIGITAL_MEDIA  =     0.06267806267806;
            Q_CategoryHR  =     0.01994301994301;
            Q_CategoryDESIGNER  =     0.02564102564102;
            Q_CategoryINFORMATION_TECHNOLOGY  =     0.02564102564102;
            Q_CategoryTEACHER  =     0.01994301994301;
            Q_CategoryADVOCATE  =      0.1082621082621;
            Q_CategoryBUSINESS_DEVELOPMENT  =     0.15669515669515;
            Q_CategoryHEALTHCARE  =     0.13675213675213;
            Q_CategoryFITNESS  =     0.04843304843304;
            Q_CategoryOTHER  =     0.14529914529914;
            Q_CategorySALES  =     0.15669515669515;
            Q_CategoryCONSULTANT  =     0.09401709401709;
            Q_CategoryDIGITAL_MEDIA  =     0.06267806267806;
            V_CategoryHR  =     0.01463414634146;
            V_CategoryDESIGNER  =     0.02439024390243;
            V_CategoryINFORMATION_TECHNOLOGY  =     0.01951219512195;
            V_CategoryTEACHER  =     0.02439024390243;
            V_CategoryADVOCATE  =     0.13658536585365;
            V_CategoryBUSINESS_DEVELOPMENT  =      0.1560975609756;
            V_CategoryHEALTHCARE  =     0.12195121951219;
            V_CategoryFITNESS  =     0.06341463414634;
            V_CategoryOTHER  =     0.12195121951219;
            V_CategorySALES  =     0.14146341463414;
            V_CategoryCONSULTANT  =     0.10731707317073;
            V_CategoryDIGITAL_MEDIA  =     0.06829268292682;
            I_Category  = 'BUSINESS-DEVELOPMENT' ;
            U_Category  = 'BUSINESS-DEVELOPMENT' ;
            END;
          END;
        END;
      END;
    END;
  END;

*****  RESIDUALS R_ *************;
IF  F_Category  NE 'HR' 
AND F_Category  NE 'DESIGNER' 
AND F_Category  NE 'INFORMATION-TECHNOLOGY' 
AND F_Category  NE 'TEACHER' 
AND F_Category  NE 'ADVOCATE' 
AND F_Category  NE 'BUSINESS-DEVELOPMENT' 
AND F_Category  NE 'HEALTHCARE' 
AND F_Category  NE 'FITNESS' 
AND F_Category  NE 'OTHER' 
AND F_Category  NE 'SALES' 
AND F_Category  NE 'CONSULTANT' 
AND F_Category  NE 'DIGITAL-MEDIA'  THEN DO; 
        R_CategoryHR  = .;
        R_CategoryDESIGNER  = .;
        R_CategoryINFORMATION_TECHNOLOGY  = .;
        R_CategoryTEACHER  = .;
        R_CategoryADVOCATE  = .;
        R_CategoryBUSINESS_DEVELOPMENT  = .;
        R_CategoryHEALTHCARE  = .;
        R_CategoryFITNESS  = .;
        R_CategoryOTHER  = .;
        R_CategorySALES  = .;
        R_CategoryCONSULTANT  = .;
        R_CategoryDIGITAL_MEDIA  = .;
 END;
 ELSE DO;
       R_CategoryHR  =  -P_CategoryHR ;
       R_CategoryDESIGNER  =  -P_CategoryDESIGNER ;
       R_CategoryINFORMATION_TECHNOLOGY  =  -P_CategoryINFORMATION_TECHNOLOGY
         ;
       R_CategoryTEACHER  =  -P_CategoryTEACHER ;
       R_CategoryADVOCATE  =  -P_CategoryADVOCATE ;
       R_CategoryBUSINESS_DEVELOPMENT  =  -P_CategoryBUSINESS_DEVELOPMENT ;
       R_CategoryHEALTHCARE  =  -P_CategoryHEALTHCARE ;
       R_CategoryFITNESS  =  -P_CategoryFITNESS ;
       R_CategoryOTHER  =  -P_CategoryOTHER ;
       R_CategorySALES  =  -P_CategorySALES ;
       R_CategoryCONSULTANT  =  -P_CategoryCONSULTANT ;
       R_CategoryDIGITAL_MEDIA  =  -P_CategoryDIGITAL_MEDIA ;
       SELECT( F_Category  );
          WHEN( 'HR'  ) R_CategoryHR  = R_CategoryHR  +1;
          WHEN( 'DESIGNER'  ) R_CategoryDESIGNER  = R_CategoryDESIGNER  +1;
          WHEN( 'INFORMATION-TECHNOLOGY'  ) R_CategoryINFORMATION_TECHNOLOGY
          = R_CategoryINFORMATION_TECHNOLOGY  +1;
          WHEN( 'TEACHER'  ) R_CategoryTEACHER  = R_CategoryTEACHER  +1;
          WHEN( 'ADVOCATE'  ) R_CategoryADVOCATE  = R_CategoryADVOCATE  +1;
          WHEN( 'BUSINESS-DEVELOPMENT'  ) R_CategoryBUSINESS_DEVELOPMENT  = 
        R_CategoryBUSINESS_DEVELOPMENT  +1;
          WHEN( 'HEALTHCARE'  ) R_CategoryHEALTHCARE  = R_CategoryHEALTHCARE
          +1;
          WHEN( 'FITNESS'  ) R_CategoryFITNESS  = R_CategoryFITNESS  +1;
          WHEN( 'OTHER'  ) R_CategoryOTHER  = R_CategoryOTHER  +1;
          WHEN( 'SALES'  ) R_CategorySALES  = R_CategorySALES  +1;
          WHEN( 'CONSULTANT'  ) R_CategoryCONSULTANT  = R_CategoryCONSULTANT
          +1;
          WHEN( 'DIGITAL-MEDIA'  ) R_CategoryDIGITAL_MEDIA  = 
        R_CategoryDIGITAL_MEDIA  +1;
       END;
 END;

****************************************************************;
******          END OF DECISION TREE SCORING CODE         ******;
****************************************************************;

